# Configuración de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://jfesanchezl_db_user:Q8889UnHsKeo9eGa@cluster0.dmgadse.mongodb.net/productos_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=productos_db

# Configuración del servidor
server.port=8080
